
export interface RefItem {
    label: string;
    code: string;
    desc?: string;
  }
  
  // 1-0 Sequence for better pattern recognition
  export const MORSE_NUMBERS: RefItem[] = [
    { label: '1', code: '.----' },
    { label: '2', code: '..---' },
    { label: '3', code: '...--' },
    { label: '4', code: '....-' },
    { label: '5', code: '.....' },
    { label: '6', code: '-....' },
    { label: '7', code: '--...' },
    { label: '8', code: '---..' },
    { label: '9', code: '----.' },
    { label: '0', code: '-----' },
  ];
  
  export const MORSE_PUNCTUATION: RefItem[] = [
    { label: '.', code: '.-.-.-', desc: '句号' },
    { label: ',', code: '--..--', desc: '逗号' },
    { label: '?', code: '..--..', desc: '问号' },
    { label: "'", code: '.----.', desc: '撇号' },
    { label: '!', code: '-.-.--', desc: '感叹号' },
    { label: '/', code: '-..-.', desc: '斜杠' },
    { label: '(', code: '-.--.', desc: '左括号' },
    { label: ')', code: '-.--.-', desc: '右括号' },
    { label: '&', code: '.-...', desc: 'Wait' },
    { label: ':', code: '---...', desc: '冒号' },
    { label: ';', code: '-.-.-.', desc: '分号' },
    { label: '=', code: '-...-', desc: '等号' },
    { label: '+', code: '.-.-.', desc: '加号' },
    { label: '-', code: '-....-', desc: '连字号' },
    { label: '_', code: '..--.-', desc: '下划线' },
    { label: '"', code: '.-..-.', desc: '引号' },
    { label: '$', code: '...-..-', desc: '美元符号' },
    { label: '@', code: '.--.-.', desc: 'At符号' },
  ];
  
  // Special Prosigns (Procedural Signals) - Sent as one character
  export const MORSE_PROSIGNS: RefItem[] = [
    { label: 'SOS', code: '...---...', desc: '紧急求救' },
    { label: 'HH', code: '........', desc: '改错/更正' },
    { label: 'BT', code: '-...-', desc: '段落/分隔符 (=)' },
    { label: 'AR', code: '.-.-.', desc: '消息结束 (+)' },
    { label: 'SK', code: '...-.-', desc: '通讯结束/再见' },
    { label: 'KA', code: '-.-.-', desc: '开始信号' },
    { label: 'AS', code: '.-...', desc: '请稍等/等待' },
  ];
  
  // Abbreviations & Q-Codes - Sent with spacing between characters
  export const MORSE_ABBR: RefItem[] = [
    { label: 'AA', code: '.- .-', desc: '某字以后 (All after)' },
    { label: 'AB', code: '.- -...', desc: '字以前 (All before)' },
    { label: 'ABT', code: '.- -... -', desc: '大约 (About)' },
    { label: 'ADS', code: '.- -.. ...', desc: '地址 (Address)' },
    { label: 'AGN', code: '.- --. -.', desc: '再一次 (Again)' },
    { label: 'ANT', code: '.- -. -', desc: '天线 (Antenna)' },
    { label: 'ARRL', code: '.- .-. .-. .-..', desc: '美国无线电中继联盟' },
    { label: 'BN', code: '-... -.', desc: '......之间 (All between)' },
    { label: 'BUG', code: '-... ..- --.', desc: '半自动电键 (Semiautomatic key)' },
    { label: 'C', code: '-.-.', desc: '是，好 (Yes)' },
    { label: 'CBA', code: '-.-. -... .-', desc: '呼号手册 (Callbook address)' },
    { label: 'CFM', code: '-.-. ..-. --', desc: '确认 (Confirm)' },
    { label: 'CLG', code: '-.-. .-.. --.', desc: '调用 (Calling)' },
    { label: 'CQ', code: '-.-. --.-', desc: '调用任意台站 (Calling any station)' },
    { label: 'CUL', code: '-.-. ..- .-..', desc: '再见 (See you later)' },
    { label: 'CUZ', code: '-.-. ..- --..', desc: '因为 (Because)' },
    { label: 'CW', code: '-.-. .--', desc: '连续波 (Continuous wave)' },
    { label: 'CX', code: '-.-. -..-', desc: '状况 (Conditions)' },
    { label: 'CY', code: '-.-. -.--', desc: '抄收 (Copy)' },
    { label: 'DE', code: '-.. .', desc: '来自 (From)' },
    { label: 'DX', code: '-.. -..-', desc: '距离/远程通联 (Distance)' },
    { label: 'ES', code: '. ...', desc: '和；且 (And)' },
    { label: 'FB', code: '..-. -...', desc: '很好/确定 (Fine business)' },
    { label: 'FCC', code: '..-. -.-. -.-.', desc: '联邦通信委员会' },
    { label: 'FER', code: '..-. . .-.', desc: '为了 (For)' },
    { label: 'FREQ', code: '..-. .-. . --.-', desc: '频率 (Frequency)' },
    { label: 'GA', code: '--. .-', desc: '午安/请发报 (Good afternoon/Go ahead)' },
    { label: 'GE', code: '--. .', desc: '晚安 (Good evening)' },
    { label: 'GM', code: '--. --', desc: '早安 (Good morning)' },
    { label: 'GND', code: '--. -. -..', desc: '地面/地电位 (Ground)' },
    { label: 'GUD', code: '--. ..- -..', desc: '好 (Good)' },
    { label: 'HI', code: '.... ..', desc: '笑声 (Laughter)' },
    { label: 'HR', code: '.... .-.', desc: '这里 (Here)' },
    { label: 'HV', code: '.... ...-', desc: '有 (Have)' },
    { label: 'LID', code: '.-.. .. -..', desc: '覆盖 (Lid)' },
    { label: 'MILS', code: '-- .. .-.. ...', desc: '毫安培 (Milliamperes)' },
    { label: 'NIL', code: '-. .. .-..', desc: '无收信/空白 (Nothing)' },
    { label: 'NR', code: '-. .-.', desc: '编号 (Number)' },
    { label: 'OB', code: '--- -...', desc: '老大哥 (Old boy)' },
    { label: 'OC', code: '--- -.-.', desc: '老伙计 (Old chap)' },
    { label: 'OM', code: '--- --', desc: '前辈/男士 (Old man)' },
    { label: 'OO', code: '--- ---', desc: '官方观察员 (Official Observer)' },
    { label: 'OP', code: '--- .--.', desc: '操作员 (Operator)' },
    { label: 'OT', code: '--- -', desc: '老前辈 (Old timer)' },
    { label: 'OTC', code: '--- - -.-.', desc: '老手俱乐部' },
    { label: 'PSE', code: '.--. ... .', desc: '请 (Please)' },
    { label: 'PWR', code: '.--. .-- .-.', desc: '功率 (Power)' },
    { label: 'R', code: '.-.', desc: '收到 (Received)' },
    { label: 'RCVR', code: '.-. -.-. ...- .-.', desc: '接收机 (Receiver)' },
    { label: 'RPT', code: '.-. .--. -', desc: '重复/报告 (Repeat/Report)' },
    { label: 'RST', code: '.-. ... -', desc: '信号报告 (Readability-Strength-Tone)' },
    { label: 'RTTY', code: '.-. - - -.--', desc: '无线电传 (Radioteletype)' },
    { label: 'RX', code: '.-. -..-', desc: '接收 (Receive)' },
    { label: 'SAE', code: '... .- .', desc: '回邮信 (Self addressed envelope)' },
    { label: 'SASE', code: '... .- ... .', desc: '带票回邮信封' },
    { label: 'SED', code: '... . -..', desc: '说 (Said)' },
    { label: 'SEZ', code: '... . --..', desc: '说 (Says)' },
    { label: 'SIG', code: '... .. --.', desc: '信号 (Signal)' },
    { label: 'SIGS', code: '... .. --. ...', desc: '信号 (Signals)' },
    { label: 'SKED', code: '... -.- . -..', desc: '行程表 (Schedule)' },
    { label: 'SN', code: '... -.', desc: '很快 (Soon)' },
    { label: 'SRI', code: '... .-. ..', desc: '抱歉 (Sorry)' },
    { label: 'STN', code: '... - -.', desc: '台站 (Station)' },
    { label: 'TEMP', code: '- . -- .--.', desc: '温度 (Temperature)' },
    { label: 'TMW', code: '- -- .--', desc: '明天 (Tomorrow)' },
    { label: 'TNX', code: '- -. -..-', desc: '谢谢 (Thanks)' },
    { label: 'TU', code: '- ..-', desc: '谢谢你 (Thank you)' },
    { label: 'TX', code: '- -..-', desc: '发射 (Transmit)' },
    { label: 'U', code: '..-', desc: '你 (You)' },
    { label: 'UR', code: '..- .-.', desc: '你的 (Your)' },
    { label: 'URS', code: '..- .-. ...', desc: '你的 (Yours)' },
    { label: 'VY', code: '...- -.--', desc: '非常 (Very)' },
    { label: 'WDS', code: '.-- -.. ...', desc: '词 (Words)' },
    { label: 'WKD', code: '.-- -.- -..', desc: '工作 (Worked)' },
    { label: 'WL', code: '.-- .-..', desc: '将会/好 (Will/Well)' },
    { label: 'WUD', code: '.-- ..- -..', desc: '将会 (Would)' },
    { label: 'WX', code: '.-- -..-', desc: '天气 (Weather)' },
    { label: 'XMTR', code: '-..- -- - .-.', desc: '发射机 (Transmitter)' },
    { label: 'XYL', code: '-..- -.-- .-..', desc: '妻子 (Wife)' },
    { label: 'YL', code: '-.-- .-..', desc: '女报务员 (Young Lady)' },
    { label: '73', code: '--... ...--', desc: '最好的祝福 (Best regards)' },
    { label: '88', code: '---.. ---..', desc: '爱与吻 (Love and kisses)' },
    { label: '99', code: '----. ----.', desc: '走开 (Go way - 非友善)' },
  ];
